Add swagger
BookCrossing-SoftServe/Bookcrossing-Back-End pull request #14
Opened 2020-03-13 20:47 UTC by Hel1ks

Closes #11 Connect Swagger to back-end

2020-03-13 20:50 UTC, VitaliyRud2001 requested changes
Make pull request into develop branche, not master.

2020-03-13 20:54 UTC, VitaliyRud2001 approved these changes

2020-03-14 09:21 UTC, VolodymyrKorpal approved these changes

2020-03-14 09:21 UTC, VolodymyrKorpal approved these changes

2020-03-14 12:22 UTC, romadmn approved these changes

2020-03-14 12:24 UTC, merged