022 create admin panel
BookCrossing-SoftServe/Bookcrossing-Back-End pull request #23
Opened 2020-03-15 19:19 UTC by romadmn

2020-03-15 23:08 UTC, Hel1ks approved these changes

2020-03-15 23:36 UTC, MaksymNovitskyi approved these changes

2020-03-16 11:53 UTC, Hel1ks requested changes
Change endpoint names

2020-03-16 11:54 UTC, VitaliyRud2001 requested changes
remove add/delete genres. We got fixed list of genres

2020-03-16 12:02 UTC, Hel1ks approved these changes

2020-03-16 12:04 UTC, MaksymNovitskyi approved these changes

2020-03-16 12:29 UTC, VitaliyRud2001 approved these changes
Nice

2020-03-16 12:29 UTC, merged