#050 Connect Azure DB
BookCrossing-SoftServe/Bookcrossing-Back-End pull request #54
Opened 2020-03-20 16:12 UTC by romadmn

- Connected Azure Db connection string
- Changed appsettings.json file in REDME.MD

2020-03-20 17:43 UTC, VitaliyRud2001 requested changes
Ok

2020-03-20 17:43 UTC, VitaliyRud2001 approved these changes

2020-03-20 19:43 UTC, MaksymNovitskyi approved these changes

2020-03-21 13:31 UTC, Hel1ks approved these changes

2020-03-21 13:32 UTC, merged